browsers:
  - identifier: chrome
    version: 100
  - identifier: firefox
    version: 100
  - identifier: edge
    version: 23
ruleOverrides:
  partially-compatible: fail
  flagged: fail
  unknown-feature: warn
featureIgnores:
  - at-rule
  - function:rgb
  - property:align-items:center
  - property:gap:20px:flex_context
fileExtensionIgnores:
  - sass
  - less
parserOptions:
  strict: false
reportOptions:
  includePerFeatureSummary: true
  outputReportFiles:
    - type: json
      location: reports/example.json
    - type: html
      location: reports/example.html
